/control/verbose 2
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

########################Output File Name########################
/ricochetchoozsim/tree/setOutputFileName RicochetChoozOutput.root

########################Source Settings########################
### source radius must be greater than source thickness
### (4250 mm is inside pit radius, so radius+0.5*thickness)
/ricochetchoozsim/generator/setsourceradius 4255 mm
### set source height must equal 7000 mm (tank height) + source thickness
/ricochetchoozsim/generator/setsourcethickness 10 mm
/ricochetchoozsim/generator/setsourceheight 8410  mm
/ricochetchoozsim/generator/setsourceheightoffset +50 mm

########################Set Shieldings########################
#/ricochetchoozsim/detector/constructADR true
#/ricochetchoozsim/shielding/setPolyshielding 19. 24. 1. cm
#/ricochetchoozsim/shielding/setLayerLength 1. m
#/ricochetchoozsim/shielding/setLayerThickness 50 mm
#/ricochetchoozsim/shielding/addLayerWithMaterial Pol

########################Set Materials########################
/ricochetchoozsim/detector/setcrystalmaterial Zn
/ricochetchoozsim/detector/setOuterDetectorMaterial G4_AIR

########################Set Source Type########################
#/ricochetchoozsim/generator/neutronsource 5000 keV
#/ricochetchoozsim/generator/SetPointNeutronSource 0 0 0 mm
/ricochetchoozsim/generator/SetNeutronSource true
/ricochetchoozsim/generator/setneutronsourcespectrum input_spectra/Joe-32GeV-10MeVthreshold.txt
#/ricochetchoozsim/generator/SetNeutronSource_xlog true
#/ricochetchoozsim/generator/genMuonFromSpectrum DC_MUSIC_sim_ND_Full_Info.root

/run/beamOn 10
