/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/ricochetchoozsim/tree/setOutputFileName ChoozWithAirMei10MeV_0.root

/ricochetchoozsim/generator/SetNeutronSource true
/ricochetchoozsim/generator/setsourceradius 4.25 m
/ricochetchoozsim/generator/setsourceheight 8.4 m
/ricochetchoozsim/generator/setneutronsourcespectrum  input_spectra/fast_neutron_spectrum_Mei-50GeV-10MeVthreshold.txt

/run/beamOn 1000
